#!/bin/bash

temp_response=$(mktemp)
docker exec main fish -c 'root/gemini/answer.sh' > "$temp_response"
sleep 1
cat "$temp_response" | wl-copy
notify-send -h string:bgcolor:#FFFFFF  -h string:fgcolor:#ADACAD "." "'done'" -t 1500


