live_config_reload = true

[window]
padding = { x = 10, y = 10 }
decorations = "None"
dynamic_padding = true
opacity = 0.89
blur = true

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
bold = { family = "SauceCodePro Nerd Font", style = "Bold" }
italic = { family = "SauceCodePro Nerd Font", style = "Italic" }
offset = { x = 0, y = 5 }
size = 19


[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }
thickness = 0.13

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
  { key = "h", mods = "Control|Shift", action = "ReceiveChar" },
  { key = "l", mods = "Control|Shift", action = "ReceiveChar" },
]
