live_config_reload = true

[window]
padding = { x = 10, y = 10 }
decorations = "None"
dynamic_padding = true
opacity = 1
blur = true

[colors]
cursor = { cursor = "#a5a5a5", text="#bebebe"}

[colors.primary]
background = '#FFFFFF'
foreground = '#bebebe'


[font]
normal = { family = "Iosevka Term", style = "Regular" }
bold = { family = "Iosevka Term", style = "Bold" }
italic = { family = "Iosevka Term", style = "Italic" }
offset = { x = 0, y = 3 }
size = 12


[cursor]
style = { shape = "Underline", blinking = "Never" }
vi_mode_style = { shape = "Underline", blinking = "Never" }

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
  { key = "h", mods = "Control|Shift", action = "ReceiveChar" },
  { key = "l", mods = "Control|Shift", action = "ReceiveChar" },
]
